//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionParty
    {
        public TransactionParty()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string TransactionPartyName { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
